version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - university-course-management:/var/lib/postgresql/data/

volumes:
  university-course-management:
    external: true
